name: R Dependency License Report
author: Insights Engineering
description: |
  A Github Action that generates a license report of an R package's dependencies for continuous compliance.
inputs:
  path:
    description: Path to package's root
    required: false
    default: .
  regex:
    description: Regex used for flagging packages with non-compliant licenses
    required: false
    default: ""
  fail:
    description: Fail with a non-zero exit code if one or more dependencies are flagged by the regex
    required: false
    default: true
  rspm_snapshot_date:
    description: RSPM snapshot date (in the YYYY-MM-DD format) for package metadata retrieval. Defaults to current date
    required: false
    default: ""
  bioc_release:
    description: BioConductor release version for package metadata retrieval
    required: false
    default: release
  output_type:
    description: Whether you also want the report as a `pdf`, or an `html` file
    required: false
    default: ""
runs:
  using: 'docker'
  image: './Dockerfile'
branding:
  icon: 'life-buoy'  
  color: 'green'
