---
name: SuperLinter

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_R: true
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_PYTHON_FLAKE8: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
