---
name: Auto-style

on:
  issue_comment:
    types:
      - created

jobs:
  style:
    if: startsWith(github.event.comment.body, '/command /style')
    name: Auto-style
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.1.0
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Fetch PR
        uses: r-lib/actions/pr-fetch@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: install.packages("styler", dependencies=TRUE, repos="http://cran.rstudio.com/")
        shell: Rscript {0}

      - name: Stylize
        run: styler::style_dir()
        shell: Rscript {0}

      - name: Commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add \*.R
          git commit -m 'Style'
      - name: Push
        uses: r-lib/actions/pr-push@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
