---
name: License report action test

on:
  pull_request:
    branches:
      - main

jobs:
  aragog:
    runs-on: ubuntu-latest
    name: Test aragog 🧪

    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v2

      - name: License report for Aragog 🕷
        uses: ./
        with:
          path: ./fixtures/packages/aragog

  buckbeak:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        output_type: ["pdf", "html"]
    name: Test buckbeak (${{ matrix.output_type }}) 🧪

    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v2

      - name: License report (${{ matrix.output_type }}) for Buckbeak 🦄
        uses: ./
        with:
          path: ./fixtures/packages/buckbeak
          regex: "AGPL.*"
          fail: true
          rspm_snapshot_date: "2021-12-12"
          bioc_release: "3.14"
          output_type: ${{ matrix.output_type }}

      - name: Upload ${{ matrix.output_type }} report ⤴
        uses: actions/upload-artifact@v2
        with:
          name: "license-report.${{ matrix.output_type }}"
          path: "license-report.${{ matrix.output_type }}"
