---
name: License report action test

on:
  pull_request:
    branches:
      - main

jobs:
  aragog:
    runs-on: ubuntu-latest
    name: Test aragog

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: License report for Aragog
        uses: ./
        with:
          path: ./fixtures/packages/aragog

  buckbeak:
    runs-on: ubuntu-latest
    name: Test buckbeak

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: License report for Buckbeak
        uses: ./
        with:
          path: ./fixtures/packages/buckbeak
          regex: "AGPL.*"
          fail: true
          rspm_snapshot_date: "2021-12-06"
          bioc_release: "3.14"
